[package]
name = "simple_ip_tools"
version = "0.1.0"
edition = "2024"

[dependencies]
ipnet = "2.9"
iptrie = "0.10.3"
csv = "1.3.1"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
thiserror = "1.0"